// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaofunhwakvuuszbunkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphb2Z1bmh3YWt2dXVzemJ1bmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NDQxNDcsImV4cCI6MjA4OTIyMDE0N30.q79dppCq66BGdqmF33Lko6XGYoYqUl9Hv-yETh-b5lQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});