// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxdrtbgsrqejeihmzqhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZHJ0YmdzcnFlamVpaG16cWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNjMzNDIsImV4cCI6MjA4NzgzOTM0Mn0._TZsfepTQRv2CDczNVZ1tA1yjMzTrijIu7qONwMe6-U";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});