// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyudxggyqdzzbdhpnzzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dWR4Z2d5cWR6emJkaHBuenpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjM1MDIsImV4cCI6MjA3MjczOTUwMn0.XozJ1j0Kw3t5FSnNWYWgPKKgrTYqfdQJ_rwo8Znfi30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});